server:
  port: 8080
spring:
  application:
    name: goya-gateway
  profiles:
    # 环境配置
    active: dev
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        # 配置中心地址
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        # 配置文件格式
        file-extension: yml
        namespace: public
    sentinel:
      # 取消控制台懒加载
      eager: true
      transport:
        # 控制台地址
        dashboard: 127.0.0.1:8718
    gateway:
      routes:
        - id: 1
          # uri: http://127.0.0.1:9001
          uri: lb://goya-system
          predicates:
            - Path=/system/**

logging:
  level:
    root: debug
    com.alibaba.nacos: info